import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import { ThemeProvider } from './components/theme-provider';
import DarkThemeHandler from "./components/theme-handler";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KHS's home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <head><DarkThemeHandler /></head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen flex-col `}>
        <ThemeProvider>
        <Nav />
        {/* <ThemeProvider>{children}</ThemeProvider> */}
        <main className="flex-1 px-8 py-8">{children}</main>

        <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
